### ISSUE TITLE
python prepare.py always error

### ISSUE THREAD

**Issue by Lseven-zzw** [karpathy/nanoGPT#113]
![image](https://user-images.githubusercontent.com/73870365/216515907-0ee76f9a-e5b8-4775-84bf-a2841b53bdc6.png)

**Comment by HanL2021** [comment]
Same

**Comment by lantiga** [comment]
What version of `datasets` do you have in your environment?

```bash
python -c "import datasets; print(datasets.__version__)"
```

It runs successfully for me with `datasets==2.9.0`

**Comment by Lseven-zzw** [comment]
> What version of `datasets` do you have in your environment?
> 
> ```shell
> python -c "import datasets; print(datasets.__version__)"
> ```
> 
> It runs successfully for me with `datasets==2.9.0`

**Comment by Lseven-zzw** [comment]
> `datasets`您的环境中有什么版本？
> 
> ```shell
> python -c "import datasets; print(datasets.__version__)"
> ```
> 
> 它为我成功运行`datasets==2.9.0`

![image](https://user-images.githubusercontent.com/73870365/217124502-464db884-1158-4156-b7e7-9a2d2c342ca6.png)
my version is 2.9.0

**Comment by lantiga** [comment]
Take a look at this, something funky with Windows Defender might be the cause https://github.com/karpathy/nanoGPT/issues/50

**Comment by Lseven-zzw** [comment]
> 看看这个，Windows Defender 的一些奇怪的东西可能是原因#50

I have looked at this and modified my environment to follow the suggestions in it

**Comment by Lseven-zzw** [comment]
Is it more friendly to run on linux？

**Comment by lantiga** [comment]
this specific problem isn't there for sure
