### ISSUE TITLE
Shakespeare fintuninig fails after yesterday's update

### ISSUE THREAD

**Issue by ptarau** [karpathy/nanoGPT#121]
First, it complains about bias=False and after helping with bias=True

python train.py config/finetune_shakespeare.py --bias=True

fails with:

traceback (most recent call last):
  File "/home/tarau/Desktop/TEMP/nanoGPT/train.py", line 171, in <module>
    model = GPT.from_pretrained(init_from, override_args)
  File "/home/tarau/Desktop/TEMP/nanoGPT/model.py", line 255, in from_pretrained
    assert sd_hf[k].shape == sd[k].shape

**Comment by ptarau** [comment]
Possible cause:

change of vocab size to 50304 that might disagree with the models used to finetune?

**Comment by karpathy** [comment]
yes that would do it, i broke checkpoint loading from gpt2... bleh i really do need tests. fixing...

**Comment by karpathy** [comment]
pushed a fix just now, i think should help

**Comment by ptarau** [comment]
Thanks, all great, shining again :-)
