### ISSUE TITLE
Segmentation fault when training shakespeare char on RTX 2080 Ti with compiled model.

### ISSUE THREAD

**Issue by jamesliu** [karpathy/nanoGPT#133]
I tried to train a baby GPT quickly with the settings provided in the config with PyTorch 2.0 on RTX 2080 Ti
python train.py config/train_shakespeare_char.py --compile=True

I got Segmentation fault when compile set to True; however, it is OK when compiling set to False
python train.py config/train_shakespeare_char.py --compile=False

Does anyone train successfully on RTX 2080Ti with compiled PyTorch 2.0 model? Thanks!

**Comment by lantiga** [comment]
From https://pytorch.org/get-started/pytorch-2.0/:
> As of today, our default backend TorchInductor supports CPUs and NVIDIA Volta and Ampere GPUs. It does not (yet) support other GPUs, xPUs or older NVIDIA GPUs.

2080 is Turing, so that might be the issue. In any case it looks like support for older GPUs will roll in by 2.0.

**Comment by dbl001** [comment]
For --compile=True, will pytorch-20 eventually support AMD GPUs with 'MPS'?
(It doesn't work now).

**Comment by lantiga** [comment]
Very possible but afaik the current focus is on nvidia gpus and intel cpus
