### ISSUE TITLE
Loss becomes nan after training for ~2000 iterations

### ISSUE THREAD

**Issue by OlympixJack** [karpathy/nanoGPT#136]
Like the title said, I've been receiving "loss: nan" after training for about 2000 iterations. The only things I changed in the script was the block size (from 1024 to 512 due to memory issue with the GPUs, I have access to Tesla V100 not A100) and I disabled wandb logging. Any ideas why this is happening? Any thoughts/suggestions are appreciated.

**Comment by PershingSquare** [comment]
Try reducing learning rate.

See this for more details
https://arxiv.org/abs/1706.02677

**Comment by OlympixJack** [comment]
Confirming this works. Thank you.

**Comment by holyseven** [comment]
@OlympixJack Hi, I reduced the learning rate to `1e-5`, and yet had the nan issue after ~6000 iters. I'd like to know whether you used `bfloat16` with V100? because i didn't manage to set it to `bfloat16` with V100 and used `float16`. I'm not sure whether it is caused by this. Thanks!
