### ISSUE TITLE
GeForce GTX 1080

### ISSUE THREAD

**Issue by vinnitu** [karpathy/nanoGPT#157]
Got

```
RuntimeError: Found NVIDIA GeForce GTX 1080 which is too old to be supported by the triton GPU compiler, which is used as the backend. Triton only supports devices of CUDA Capability >= 7.0, but your device is of CUDA capability 6.1
```

Is it really not impossible use 1080 in this project?

**Comment by ZacharyZhang-NY** [comment]
you can change the train.py file
`backend = 'nccl'` 
to
`backend = 'gloo'`
and
`dtype = 'bfloat16'`
to
`dtype = 'float32'`

**Comment by ZacharyZhang-NY** [comment]
Tried this on nvidia P40 which is the same arch with 1080

**Comment by ZacharyZhang-NY** [comment]
also nees to set compile = False

**Comment by drtonyr** [comment]
Thanks for this thread.  'compile = False' was what I needed for TITAN X.
