### ISSUE TITLE
Expected dataset format

### ISSUE THREAD

**Issue by nirvitarka** [karpathy/nanoGPT#172]
Following the same steps as described here for the Shakespere input file, I tried this on a custom input file which contains multiple paragraphs with different headings. The file contents looks like this

**Heading 1
Some information related to heading 1 goes here

Heading 2
Some information related to heading 2 goes here**

Containing 20 such paragraphs.

The "prepare.py" and "train.py" file executed successfully for this input file.
However, when I try to generate one sample, the output is some incorrect english like this

`paceliYai ominger fromally.Satexas Stence taly mand gollag adeppirirhon temas poymais,Mcenterted Should had & days to suratication tEO - ande ymanaN tor reeson travel from the enterns tleat sompoyers asubve the candidate can travel cof grotef dosiction of inotis, an too coan cile verand ginald to Employees. All embent ire thang falor ind the to pacomvertaly of the is enotiry for `

Is this input dataset format correct? Or something specific is needed?

**Comment by venzen** [comment]
Your dataset's text format is unlikely to cause the above non-English word sample. Are you perhaps using the shakespeare\_char _prepare.py_ and _train\_shakespeare\_char.py_ code? The output seems to be character prediction...

**Comment by nirvitarka** [comment]
Yes I was trying it with "_char", thank you @venzen for pointing out that. 
Now I am training using scripts under "...shakespeare/prepare.py", will update the outcome here as soon as the training gets finished.

**Comment by nirvitarka** [comment]
Yes it worked with the "non-char" approach
