### ISSUE TITLE
running prepare.py on a very large dataset

### ISSUE THREAD

**Issue by aartivnkt** [karpathy/nanoGPT#176]
Hi there, I have a custom dataset that is quite large ~40GB, similar to the openwebtext data you present as an example. My dataset is not in huggingface, and running prepare.py on a standard GPU node throws MemoryError while reading. Do you have any suggestions on how we might read and tokenize a very large dataset of this sort? Can we split it into different chunks, tokenize each chunk and combine? Or other strategies? Thanks so much for any input

**Comment by vgoklani** [comment]
I would use an iterable dataset: 

https://github.com/karpathy/nanoGPT/issues/70

**Comment by aartivnkt** [comment]
Thanks so much for that! I'll take a look. 

I'm new to tokenization, one naive question is will reading a file line by line work? Example:
```
encoding = tiktoken.get_encoding("gpt2")
tokens_list = []
for line in file:
   tokens_list.append(encoding.encode(line))

```

**Comment by venzen** [comment]
Tokenizing as you propose - read a line,  tokenize it. write it to file, repeat - could work. However, the final step of creating a _train.bin_ and _val.bin_ files of the tokenized data will still run out of memory on your system.  The reason, just to state the obvious, is that the entire tokenized set (e.g. train.txt) must be loaded into memory and pickled into binary format in order to create _train.bin_.

If you want to use the existing code in _prepare.py_ and _train.py_ you'll either need more memory or have to choose a smaller dataset that will fit in available memory.

The alternative, is to replace the use of a single monolithic pickle object in the two files mentioned, with code that uses a database to store individual pickles of tokenized lines, and then access line objects individually on each training iteration. Perhaps such a solution can be found on the web.

**Comment by aartivnkt** [comment]
Thanks so much for the `datasets` suggestion! I'll give that a shot and see what happens. May just need a larger memory machine. Do you know how to calculate the memory requirements based on input size? My GPU node has 65GB total memory and dataset is ~40GB and I thought it should be okay, but it crashed with memoryerror. Any tips on how to estimate requirements would be great! Thanks so much again.

**Comment by venzen** [comment]
@aartivnkt unfortunately I cannot advise about GPU - don't have one and know naathing :)

**Comment by aartivnkt** [comment]
Thanks so much! I worked on a very small dataset and `prepare.py` and `train.py` worked like a charm with no changes! Now I'm facing the true challenge trying to load the whole thing :)

**Comment by aartivnkt** [comment]
BTW @venzen just a quick update I revisited this issue today. I tried your suggestion of using huggingface to load the entire dataset (~30GB text file) and got a little further (yay!). It is able to load the dataset from a cache. However I see an incorrect output for length of the dataset, and getting `tokens_list` using `encoding.encode(data)` returns an error in tiktoken. I'm looking into this further to see why this is happening. Here is the log:

```
python prepare.py

Found cached dataset text (/home/aartiv/.cache/huggingface/datasets/text/default-ae83484594c4a340/0.0.0/cb1e9bd71a82ad27976be3b12b407850fe2837d80c22c5e03a28949843a8ace2)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.36s/it]
length of dataset is: 1
Traceback (most recent call last):
  File "prepare.py", line 23, in <module>
    tokens_list = encoding.encode(data)
  File "/home/aartiv/.pyenv/versions/venv-380/lib/python3.8/site-packages/tiktoken/core.py", line 111, in encode
    if match := _special_token_regex(disallowed_special).search(text):
TypeError: expected string or buffer
```
I'll update if I find out why this is happening. Alternately, I might need to look into what @vgoklani posted as a solution, to create a dataset iterable. Or other ways to chunk datasets individually, tokenize and train.

**Comment by aartivnkt** [comment]
Update: I made my large dataset an iterable dataset. Iterating through the examples, I'm currently doing something very simple. For every 4.5 million examples, output a `train.bin` and `val.bin`, and restart, emptying out tokens, len and `np.memmap`. Then I plan on running `train.py` on each of these smaller `train.bin` and `val.bin` files, iteratively generating a model.ckpt and using it for the subsequent iteration of training. Hoping this somewhat works!

**Comment by aartivnkt** [comment]
I trained on multiple batches and got this to work, and what I have right now is a document completer. I'll close this issue.
