### ISSUE TITLE
Incorrect GPU count used for gradient_accumulation_steps

### ISSUE THREAD

**Issue by nmharmon8** [karpathy/nanoGPT#283]
Currently the gradient_accumulation_steps is adjusted by the device_count not the world size. This can be a problem if you don't run with all the available GPUs. 

Original 
``` python 
assert gradient_accumulation_steps % torch.cuda.device_count() == 0
gradient_accumulation_steps //= torch.cuda.device_count()
```
Suggestion 
``` python
assert ddp_world_size <= torch.cuda.device_count()
assert gradient_accumulation_steps % ddp_world_size == 0
gradient_accumulation_steps //= ddp_world_size
```

**Comment by nmharmon8** [comment]
See pull request #284

**Comment by karpathy** [comment]
fixed here https://github.com/karpathy/nanoGPT/commit/7339b904ef0bb8f4dcc88e4d602c04271697279f
