### ISSUE TITLE
Different inference results from CPU and GPU.

### ISSUE THREAD

**Issue by yu-zou** [karpathy/nanoGPT#344]
Is it an expected behavior that running the same GPT2 inference generates two different sequences on CPU and GPU?

The command to run on GPU:
python sample.py --init_from=gpt2 --start="I'm a language model." --max_new_tokens=$max_new_tokens --num_samples=1

The command to run on CPU:
python sample.py --init_from=gpt2 --start="I'm a language model." --max_new_tokens=$max_new_tokens --num_samples=1 --device=cpu

GPU inference result:
![image](https://github.com/karpathy/nanoGPT/assets/11840520/635d51f4-589a-4f1d-9f10-3815f181a51f)

CPU inference result:
![image](https://github.com/karpathy/nanoGPT/assets/11840520/97edb86d-83ef-49da-aecc-b7f8400bb314)

Inside sample.py file, the random seed is fixed:
seed = 1337

**Comment by karpathy** [comment]
Can you try with temperature zero?

**Comment by karpathy** [comment]
Why close?
