### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by agamemnonc** [karpathy/nanoGPT#35]
Andrej, thank you for everything -- you have been a great teacher to many of us.

Please feel free to close this issue now :)

**Comment by okpatil4u** [comment]
I would advise against it. Allow the admiration to come naturally. This has been an important learning experience from a pioneering figure in the industry.

**Comment by omar2205** [comment]
> I would advise against it. Allow the admiration to come naturally. This has been an important learning experience from a pioneering figure in the industry.

If @karpathy were to turn on Discussions, it can be turned into one.
