### ISSUE TITLE
Some conceptual questions regarding wte and wpe in model.py

### ISSUE THREAD

**Issue by zyzhang1130** [karpathy/nanoGPT#370]
Hi, I have some conceptual question would like to clarify. It seems both wte and wpe in model.py are trainable nn.Embedding layers, but I thought at least positional encoding should be hardcoded. Is my understanding on the concept or the code here wrong?

**Comment by sergeybok** [comment]
Positional encodings _were_ "hardcoded" in the attention is all you need paper. But GPT-style models learn their positional encodings (as do most LLMs iirc).
