### ISSUE TITLE
The function get_lr is not being utilized in the train.py

### ISSUE THREAD

**Issue by aistream69** [karpathy/nanoGPT#425]
Although int the line 255:     

lr = get_lr(iter_num) if decay_lr else learning_rate

However, the variable lr does not play any role throughout the entire training proess.

**Comment by VatsaDev** [comment]
Pytorch optimizers (https://pytorch.org/docs/stable/optim.html), the variable LR is given to the param_groups, line 256:

``` python
for param_group in optimizer.param_groups:
        param_group['lr'] = lr
```

**Comment by aistream69** [comment]
oh, sorry, it was my oversight, thank you.
