### ISSUE TITLE
Why is there no mask when using flash attention?

### ISSUE THREAD

**Issue by bruce2233** [karpathy/nanoGPT#451]
https://github.com/karpathy/nanoGPT/blob/325be85d9be8c81b436728a420e85796c57dba7e/model.py#L61-L71

If so, is GPT a decoder-only transformer?

**Comment by muerghq** [comment]
is_causal=True applies the causal masking. "attn_mask" in the function allows user to pass user-defined attention masking. User one of them to set the masking. You will get an error if both are set.

What this repo implemented is a decoder-only transformer with causal masking. If no mask is applied, it's an encoder-only transformer.
