### ISSUE TITLE
[Question] why bias is init to zero?

### ISSUE THREAD

**Issue by michael8090** [karpathy/nanoGPT#472]
Frist thanks for the wonderful project. I learn a lot by reading the code.

https://github.com/karpathy/nanoGPT/blob/325be85d9be8c81b436728a420e85796c57dba7e/model.py#L166

I see the biasis are inited to zeros, but it should have no effect (bacuase y = weights * x + bias in `Linear`), which is the same as set `config.bias` to `False`. Do I understand it correctly?

**Comment by karpathy** [comment]
it's not the same. this is init to zero but trainable.
