### ISSUE TITLE
Got stucked at the "dataset = load_dataset("openwebtext")

### ISSUE THREAD

**Issue by HanL2021** [karpathy/nanoGPT#49]
The last outputs are "
Downloading builder script: 2.86kB [00:00, 3.19MB/s]                                                         
Downloading builder script: 2.86kB [00:00, 3.01MB/s]                                                         
Downloading builder script: 2.86kB [00:00, 3.07MB/s]                                                         
Downloading builder script: 2.86kB [00:00, 2.45MB/s]                                                         
Downloading builder script: 2.86kB [00:00, 2.98MB/s]                                                         
Downloading metadata: 1.15kB [00:00, 1.24MB/s]                                                               
Downloading builder script: 2.86kB [00:00, 3.08MB/s]                                                         
Downloading metadata: 1.15kB [00:00, 1.47MB/s]                                                               
Downloading metadata: 1.15kB [00:00, 1.21MB/s]                                                               
Downloading metadata: 1.15kB [00:00, 1.45MB/s]                                                               
Downloading metadata: 1.15kB [00:00, 1.49MB/s]                                                               
Downloading metadata: 1.15kB [00:00, 1.11MB/s]    ", 
and the code keeps being pending.

**Comment by vgoklani** [comment]
It might be a better idea to remove the `datasets` dependency, and just download/parse the files directly.

**Comment by borisbolliet** [comment]
Here you will find the tokenized [train.bin](https://drive.google.com/file/d/103FjPUK_PZRmNJtpuH52xtVPxEjSoJT8/view?usp=sharing) (~8.5MB) and [val.bin](https://drive.google.com/file/d/1G_NwEsLP2jNMxkq6tehfejzkPymsBfcn/view?usp=drive_link) (~17GB) obtained following strictly the @karpathy's [script](https://github.com/karpathy/nanoGPT/blob/master/data/openwebtext/prepare.py).
