### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by HanL2021** [karpathy/nanoGPT#61]
Run on an NVIDIA V100 PCIe3 32GB and got the following OOM error after the step 0:

RuntimeError: CUDA out of memory. Tried to allocate 786.00 MiB (GPU 0; 15.78 GiB total capacity; 14.28 GiB already allocated; 620.69 MiB free; 14.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by rwang7839** [comment]
Use a smaller batch size?

**Comment by HanL2021** [comment]
> Use a smaller batch size?

Not even working for batch size = 1 or 2.
Besides, using GPU(with x10) is much slower than using CPU (x1).
I'm using a hpc cluster.

**Comment by phamkhactu** [comment]
@HanL2021 have you solve it, I had change:
```
batch_size: 1
block_size: 8
``
but get error about memmory
