### ISSUE TITLE
More a question - is there an easy way to test generation?

### ISSUE THREAD

**Issue by fblissjr** [karpathy/nanoGPT#65]
Hi, love this project as a way to learn from scratch with local development. I was able to finetune the model, generate the checkpoints, generate the samples.

Is there an easy way to test out text generation (ie: Complete the text mask, or Q&A?) Tried combining a few different other projects out there and can't figure it out easily - it spits out Shakespeare samples only. 

Am I trying to do something that isn't possible? :)

**Comment by xiningnlp** [comment]
you can test text generation by simply running, either empty prompt or customized prompt can be used, see code of 'sample.py' for details:

`
$ python sample.py
`
