### ISSUE TITLE
token_embedding and pos_embedding

### ISSUE THREAD

**Issue by pure-water** [karpathy/nanoGPT#83]
Jusst not quite get it why the token_embedding and pos_embedding can be added linearly?

**Comment by boblucas** [comment]
Maybe read the subsection [Token/Position embedding rivalry](https://www.lesswrong.com/posts/BMghmAxYxeSdAteDc/an-exploration-of-gpt-2-s-embedding-weights). In short, why concat them (the obvious alternative), both are learned so they can easily be transformed to be orthogonal in so far as that's required, but this way you can find more interesting representations.

**Comment by karpathy** [comment]
Yes, adding is more powerful than concatenating, and the addition can implement concat if it wants to.
