### ISSUE TITLE
Source for downloading train.bin and val.bin?

### ISSUE THREAD

**Issue by lakaschus** [karpathy/nanoGPT#99]
Generating the train and validation splits takes a lot of time, on my machine it is projected to take around 15 hours. I started it yesterday and something went wrong, now I have to restart generating the splits. 
Long story, short question: Would anyone be so kind and provide the train.bin and val.bin on some cloud for download? 
This would save a lot of time and computational resources for many. :)

**Comment by karpathy** [comment]
hmmm maybe i should accept that PR that speeds it up. train.bin is 17GB right now...

**Comment by lakaschus** [comment]
I just wanted to play around a little bit with the model and do some small experiments. I found a smaller openwebtext sample that satisfies my needs for now: [stas/openwebtext-10k](https://huggingface.co/datasets/stas/openwebtext-10k)

**Comment by Skylion007** [comment]
Working on speeding up the initial downloading of openwebtext currently as well.
